coverage:
  status:
    project:
      default:
        # auto compares coverage to the previous base commit
        target: auto
        # adjust accordingly based on how flaky your tests are
        # this allows a 10% drop from the previous base commit coverage
        threshold: 10%
        # non-blocking status checks
        informational: true
        only_pulls: true

comment:
  # sections shown in the PR comment
  layout: "reach, diff, flags, files"
  # updates the comment on PRs when coverage changes
  behavior: default

flags:
  datachain:
    paths:
      - src/datachain
