version: 2

updates:
  - directory: "/"
    package-ecosystem: "pip"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"

  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
