name: Examples

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
  push: # to remove

env:
  FORCE_COLOR: "1"

jobs:
  run:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest-16-cores, macos-latest, windows-latest-8-cores]
        pyv: ['3.9', '3.12']
        group: ['get_started', 'llm_and_nlp or computer_vision', 'multimodal']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.pyv }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyv }}
          cache: 'pip'

      - name: Upgrade nox and uv
        run: |
          python -m pip install --upgrade 'nox[uv]'
          nox --version
          uv --version

      - name: Run examples
        run: nox -s examples -p ${{ matrix.pyv }} -- -m "${{ matrix.group }}"
